__merge__: ../../api/base_method.yaml

name: transcriptformer_mlflow
label: TranscriptFormer (MLflow model)
summary: "Context-aware representations of single-cell transcriptomes by jointly modeling genes and transcripts"
description: |
  TranscriptFormer is designed to learn rich, context-aware representations of
  single-cell transcriptomes while jointly modeling genes and transcripts using
  a novel generative architecture.

  It is a family of generative foundation models representing a cross-species
  generative cell atlas trained on up to 112 million cells spanning 1.53 billion
  years of evolution across 12 species.

  Here, we use a version packaged as an MLflow model.
references:
  doi:
    - 10.1101/2025.04.25.650731
links:
  documentation: https://github.com/czi-ai/transcriptformer#readme
  repository: https://github.com/czi-ai/transcriptformer

info:
  method_types: [embedding]
  preferred_normalization: counts

arguments:
  - name: --model
    type: file
    description: |
      An MLflow model URI for the transcriptformer model. If it is a .zip or
      .tar.gz file it will be extracted to a temporary directory.
    required: true

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  - path: /src/utils/exit_codes.py
  - path: /src/utils/unpack.py
  - path: /src/utils/mlflow.py
  - path: requirements.txt

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    __merge__: /src/utils/mlflow_docker_setup.yaml

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu, gpu]
