import anndata as ad
import sys
import mlflow.pyfunc
from tempfile import NamedTemporaryFile
import os
import pandas as pd

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
    "input": "resources_test/.../input.h5ad",
    "output": "output.h5ad",
    "model": "resources_test/.../model",
}
meta = {"name": "transcriptformer_mlflow"}
## VIASH END

sys.path.append(meta["resources_dir"])
from read_anndata_partial import read_anndata
from exit_codes import exit_non_applicable

print(f"====== TranscriptFormer (MLflow model) ======", flush=True)

print("\n>>> Reading input files...", flush=True)
print(f"Input H5AD file: '{par['input']}'", flush=True)
adata = read_anndata(par["input"], X="layers/counts", obs="obs", var="var", uns="uns")

if adata.uns["dataset_organism"] != "homo_sapiens":
    exit_non_applicable(
        f"Transcriptformer can only be used with human data "
        f"(dataset_organism == \"{adata.uns['dataset_organism']}\")"
    )

print(adata, flush=True)

print("\n>>> Writing temporary H5AD file...", flush=True)
input_adata = ad.AnnData(X = adata.X.copy(), var = adata.var.filter(items=["feature_id"]).rename(columns = {"feature_id": "ensembl_id"}))
input_adata.obs["assay"] = "unknown" # Avoid error if assay is missing
print(input_adata, flush=True)
h5ad_file = NamedTemporaryFile(suffix=".h5ad", delete=False)
print(f"Temporary H5AD file: '{h5ad_file.name}'", flush=True)
input_adata.write(h5ad_file.name)
del input_adata

print("\n>>> Loading model...", flush=True)
model = mlflow.pyfunc.load_model(par["model"])

print("\n>>> Running model...", flush=True)
input_df = pd.DataFrame({"input_uri": [h5ad_file.name]})
embedding = model.predict(input_df)

print("\n>>> Storing output...", flush=True)
output = ad.AnnData(
    obs=adata.obs[[]],
    var=adata.var[[]],
    obsm={
        "X_emb": embedding,
    },
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "normalization_id": adata.uns["normalization_id"],
        "method_id": meta["name"],
    },
)
print(output)

print("\n>>> Writing output to file...", flush=True)
print(f"Output H5AD file: '{par['output']}'", flush=True)
output.write_h5ad(par["output"], compression="gzip")

print("\n>>> Cleaning up temporary files...", flush=True)
h5ad_file.close()
os.unlink(h5ad_file.name)

print("\n>>> Done!", flush=True)
