__merge__: /src/api/comp_metric.yaml
name: isolated_label_asw
info:
  metric_type: embedding
  metrics:
    - name: isolated_label_asw
      label: Isolated label ASW
      summary: Evaluate how well isolated labels separate by average silhouette width
      description: |
        Isolated cell labels are defined as the labels present in the least number
        of batches in the integration task. The score evaluates how well these isolated labels
        separate from other cell identities.

        The isolated label ASW score is obtained by computing the
        ASW of isolated versus non-isolated labels on the PCA embedding (ASW metric above) and
        scaling this score to be between 0 and 1. The final score for each metric version
        consists of the mean isolated score of all isolated labels.
      references:
        doi: 10.1038/s41592-021-01336-8
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - scib==1.1.7
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, lowcpu]
