# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: unsupervised_scmerge2
# A relatively short label, used when rendering visualisations (required)
label: unsupervised Scmerge2
# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "scMerge2 is an algorithm that integrates multiple single-cell RNA-seq datasets by leveraging factor analysis of stably expressed genes and pseudoreplication."
# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  scMerge works by integrating multiple single-cell RNA-seq datasets while correcting for batch effects and preserving biological signals.
  It first identifies a set of stably expressed genes (SEGs) that are assumed to remain consistent across datasets.
  Then, it uses a factor analysis model on these SEGs to estimate and remove unwanted variation.
  To improve accuracy, scMerge creates pseudo-replicates which serve as anchors for alignment.
  Finally, it corrects the data using these estimates, producing a harmonized expression matrix suitable for downstream analysis.
references:
  doi: 
    - 10.1073/pnas.1820006116
#   bibtex:
#     - |
#       @article{foo,
#         title={Foo},
#         author={Bar},
#         journal={Baz},
#         year={2024}
#       }
links:
  # URL to the documentation for this method (required).
  documentation: https://sydneybiox.github.io/scMerge/articles/scMerge2.html
  # URL to the code repository for this method (required).
  repository: https://github.com/SydneyBioX/scMerge



# Metadata for your component
info:
  # Which normalisation method this component prefers to use (required).
  preferred_normalization: log_cpm

# Component-specific parameters (optional)
# arguments:
#   - name: "--n_neighbors"
#     type: "integer"
#     default: 5
#     description: Number of neighbors to use.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: r_script
    path: script.R
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_r:1.0.0
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: apt
        packages: cmake
      - type: r
        bioc: 
        - scmerge

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
