name: precompute_clustering_run
namespace: data_processors
label: Run clustering precomputations
summary: Run clustering on the input dataset
arguments:
  - name: --input
    type: file
    direction: input
    required: true
  - name: --output
    type: file
    direction: output
    required: true
  - type: double
    name: resolution
    default: 0.8
    description: Resolution parameter for clustering
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - scanpy
          - igraph
          - leidenalg
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, midmem, lowcpu]
