__merge__: /src/api/comp_metric.yaml
name: lisi
info:
  metric_type: graph
  metrics:
    - name: ilisi
      label: iLISI
      summary: Local inverse Simpson's Index
      description: |
        Local Inverse Simpson's Index metrics adapted from Korsunsky et al. 2019 to run on
        all full feature, embedding and kNN integration outputs via shortest path-based
        distance computation on single-cell kNN graphs. The metric assesses whether clusters
        of cells in a single-cell RNA-seq dataset are well-mixed across a categorical batch
        variable.

        The original LISI score ranges from 0 to the number of categories, with the latter
        indicating good cell mixing. This is rescaled to a score between 0 and 1.
      references:
        doi: 10.1038/s41592-021-01336-8
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
    - name: clisi
      label: cLISI
      summary: Local inverse Simpson's Index
      description: |
        Local Inverse Simpson's Index metrics adapted from Korsunsky et al. 2019 to run on
        all full feature, embedding and kNN integration outputs via shortest path-based
        distance computation on single-cell kNN graphs. The metric assesses whether clusters
        of cells in a single-cell RNA-seq dataset are well-mixed across a categorical cell type variable.

        The original LISI score ranges from 0 to the number of categories, with the latter indicating good cell mixing. This is rescaled to a score between 0 and 1.
      references:
        doi: 10.1038/s41592-021-01336-8
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi:
          - git+https://github.com/theislab/scib.git@v1.1.5
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, lowcpu]
