__merge__: ../../api/base_method.yaml

name: geneformer_mlflow
label: Geneformer (MLflow model)
summary: Geneformer is a foundation transformer model pretrained on a large-scale corpus of single cell transcriptomes
description: |
  Geneformer is a foundation transformer model pretrained on a large-scale
  corpus of single cell transcriptomes to enable context-aware predictions in
  network biology. For this task, Geneformer is used to create a batch-corrected
  cell embedding.

  Here, we use a version packaged as an MLflow model.
references:
  doi:
    - 10.1038/s41586-023-06139-9
    - 10.1101/2024.08.16.608180
links:
  documentation: https://geneformer.readthedocs.io/en/latest/index.html
  repository: https://huggingface.co/ctheodoris/Geneformer

info:
  method_types: [embedding]
  preferred_normalization: counts

arguments:
  - name: --model
    type: file
    description: |
      An MLflow model URI for the Geneformer model. If it is a .zip or
      .tar.gz file it will be extracted to a temporary directory.
    required: true

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  - path: /src/utils/exit_codes.py
  - path: /src/utils/unpack.py
  - path: /src/utils/mlflow.py
  - path: requirements.txt

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    __merge__: /src/utils/mlflow_docker_setup.yaml

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu, gpu]
