__merge__: /src/api/comp_method.yaml
name: scvi
label: scVI
summary: scVI combines a variational autoencoder with a hierarchical Bayesian model.
description: |
  scVI combines a variational autoencoder with a hierarchical Bayesian model. It uses the negative binomial distribution to describe gene expression of each cell, conditioned on unobserved factors and the batch variable. ScVI is run as implemented in Luecken et al.
references:
  doi: 10.1038/s41592-018-0229-2
links:
  repository: https://github.com/scverse/scvi-tools
  documentation: https://docs.scvi-tools.org/en/stable/user_guide/models/scvi.html
info:
  method_types: [embedding]
  preferred_normalization: counts
  variants:
    scvi_full_unscaled:
arguments:
  - name: --n_hvg
    type: integer
    default: 2000
    description: Number of highly variable genes to use.
  - name: --n_latent
    type: integer
    default: 30
    description: Number of latent dimensions.
  - name: --n_hidden
    type: integer
    default: 128
    description: Number of hidden units.
  - name: --n_layers
    type: integer
    default: 2
    description: Number of layers.
  - name: --max_epochs
    type: integer
    example: 400
    description: Maximum number of epochs.
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        pypi:
          - scvi-tools>=1.1.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, lowcpu, gpu]
