__merge__: /src/api/comp_method.yaml
name: batchelor_fastmnn
label: batchelor fastMNN
summary: Fast mutual nearest neighbors correction
description: |
  The fastMNN() approach is much simpler than the original mnnCorrect() algorithm, and proceeds in several steps.

  1. Perform a multi-sample PCA on the (cosine-)normalized expression values to reduce dimensionality.
  2. Identify MNN pairs in the low-dimensional space between a reference batch and a target batch.
  3. Remove variation along the average batch vector in both reference and target batches.
  4. Correct the cells in the target batch towards the reference, using locally weighted correction vectors.
  5. Merge the corrected target batch with the reference, and repeat with the next target batch.
references:
  # Haghverdi, L., Lun, A., Morgan, M. et al.
  # Batch effects in single-cell RNA-sequencing data are
  # corrected by matching mutual nearest neighbors.
  # Nat Biotechnol 36, 421–427 (2018). https://doi.org/10.1038/nbt.4091
  doi: 10.1038/nbt.4091
links:
  repository: https://github.com/LTLA/batchelor
  documentation: https://bioconductor.org/packages/batchelor/
info:
  method_types: [embedding]
  preferred_normalization: log_cp10k
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc: batchelor
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowcpu, highmem, hightime]
