__merge__: /src/api/comp_transformer.yaml
name: transform
label: Transform outputs
summary: Transform batch integration outputs where necessary
description: |
  Transform corrected feature output to an embedding, and an embedding to a graph output.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: scanpy
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, midmem, lowcpu]
