__merge__: ../../api/comp_method.yaml

name: scgpt
label: scGPT
summary: "A foundation model for single-cell biology"
description: |
  scGPT is a foundation model for single-cell biology based on a generative
  pre-trained transformer and trained on a repository of over 33 million cells.
  Here, we use zero-shot output from a pre-trained model to get an integrated
  embedding for the batch integration task.
references:
  doi:
    - 10.1038/s41592-024-02201-0
links:
  documentation: https://scgpt.readthedocs.io/en/latest/
  repository: https://github.com/bowang-lab/scGPT

info:
  preferred_normalization: counts

# Component-specific parameters (optional)
# arguments:
#   - name: "--n_neighbors"
#     type: "integer"
#     default: 5
#     description: Number of neighbors to use.

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        pypi:
          - "flash-attn<1.0.5"
          - scgpt

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu, gpu]
