__merge__: ../../api/comp_method.yaml
name: drvi
label: DRVI
summary: "DrVI is an unsupervised generative model capable of learning non-linear interpretable disentangled latent representations from single-cell count data."
description: |
  Disentangled Representation Variational Inference (DRVI) is an unsupervised deep generative model designed for integrating single-cell RNA sequencing (scRNA-seq) data across different batches.
  It extends the variational autoencoder (VAE) framework by learning a latent representation that captures biological variation while disentangling and correcting for batch effects.
  DRVI conditions both the encoder and decoder on batch covariates, allowing it to explicitly model and mitigate batch-specific variations during training.
  By incorporating a KL-divergence regularization term, it balances data reconstruction with latent space structure, resulting in a unified embedding where similar cells cluster together regardless of batch.
references:
  doi: 
    - 10.1101/2024.11.06.622266
links:
  documentation: https://drvi.readthedocs.io/latest/index.html
  repository: https://github.com/theislab/DRVI?tab=readme-ov-file
info:
  preferred_normalization: counts
arguments:
  - name: --n_hvg
    type: integer
    default: 2000
    description: Number of highly variable genes to use.
  - name: --n_epochs
    type: integer
    default: 100
    description: Number of epochs
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0 
    setup:
      - type: python
        pypi:
        - drvi-py==0.1.7
        - torch==2.3.0
        - torchvision==0.18.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,lowcpu,gpu]
