__merge__: /src/api/comp_transformer.yaml
name: clustering
label: Clustering
summary: Precompute clustering on the input dataset
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: scanpy
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, midmem, lowcpu]
