import anndata as ad

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_integrated': 'resources_test/.../integrated.h5ad',
  'input_solution': 'resources_test/.../solution.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'scgraph'
}
## VIASH END

print('Reading input files', flush=True)
input_integrated = ad.read_h5ad(par['input_integrated'])
input_solution = ad.read_h5ad(par['input_solution'])

print('Compute metrics', flush=True)
# metric_ids and metric_values can have length > 1
# but should be of equal length
uns_metric_ids = [ 'scgraph' ]
uns_metric_values = [ 0.5 ]

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
  
)
output.write_h5ad(par['output'], compression='gzip')
