name: process_datasets
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        __merge__: /src/api/file_common_dataset.yaml
        required: true
        direction: input
  - name: Outputs
    arguments:
      - name: "--output_dataset"
        __merge__: /src/api/file_dataset.yaml
        required: true
        direction: output
      - name: "--output_solution"
        __merge__: /src/api/file_solution.yaml
        required: true
        direction: output
  - name: Clustering
    arguments:
      - name: "--resolutions"
        type: double
        multiple: true
        default: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
        description: Resolution parameter for clustering

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: validation/check_dataset_with_schema
    repository: openproblems
  - name: data_processors/process_dataset
  - name: data_processors/precompute_clustering_run
  - name: data_processors/precompute_clustering_merge

runners:
  - type: nextflow
