name: process_integration
namespace: data_processors

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input_dataset"
        # __merge__: /src/api/file_dataset.yaml
        type: file
        direction: input
        required: true
      - name: "--input_integrated"
        # __merge__: /src/api/file_solution.yaml
        type: file
        direction: input
        required: true
      - name: --expected_method_types
        type: string
        direction: input
        required: true
        multiple: true
        description: |
          The expected output types of the batch integration method.
        choices: [ feature, embedding, graph ]
  - name: Outputs
    arguments:
      - name: "--output"
        type: file
        required: true
        direction: output
        # description: A yaml file containing the scores of each of the methods
        # default: score_uns.yaml
  - name: Clustering
    arguments:
      - name: "--resolutions"
        type: double
        multiple: true
        default: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
        description: Resolution parameter for clustering

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

dependencies:
  - name: data_processors/transform
  - name: data_processors/precompute_clustering_run
  - name: data_processors/precompute_clustering_merge

runners:
  - type: nextflow
