__merge__: /src/api/comp_method.yaml
name: batchelor_mnn_correct
label: batchelor mnnCorrect
summary: Mutual nearest neighbors correction
description: |
  Correct for batch effects in single-cell expression data using the mutual nearest neighbors method.
references:
  # Haghverdi, L., Lun, A., Morgan, M. et al.
  # Batch effects in single-cell RNA-sequencing data are
  # corrected by matching mutual nearest neighbors.
  # Nat Biotechnol 36, 421–427 (2018). https://doi.org/10.1038/nbt.4091
  doi: 10.1038/nbt.4091
links:
  repository: https://github.com/LTLA/batchelor
  documentation: https://bioconductor.org/packages/batchelor/
info:
  method_types: [feature]
  preferred_normalization: log_cp10k
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc:
          - batchelor
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowcpu, highmem, hightime]
