__merge__: /src/api/comp_method.yaml
name: mnn_correct
label: mnnCorrect
summary: Correct for batch effects in single-cell expression data using the mutual
  nearest neighbors method.
description: |
  We present a strategy for batch correction based on the detection of mutual nearest neighbors (MNNs) in the high-dimensional expression space.
  Our approach does not rely on predefined or equal population compositions across batches; instead, it requires only that a subset of the population be shared between batches.
references:
  doi: 10.1038/nbt.4091
links:
  repository: https://code.bioconductor.org/browse/batchelor/
  documentation: https://bioconductor.org/packages/batchelor/
info:
  method_types: [feature]
  preferred_normalization: log_cp10k
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc:
          - batchelor
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, lowcpu, highmem]
