__merge__: ../../api/base_method.yaml

name: uce_mlflow
label: UCE (MLflow model)
summary: UCE offers a unified biological latent space that can represent any cell
description: |
  Universal Cell Embedding (UCE) is a single-cell foundation model that offers a
  unified biological latent space that can represent any cell, regardless of
  tissue or species

  Here, we use a version packaged as an MLflow model.
references:
  doi:
    - 10.1101/2023.11.28.568918
links:
  documentation: https://github.com/snap-stanford/UCE/blob/main/README.md
  repository: https://github.com/snap-stanford/UCE

info:
  method_types: [embedding]
  preferred_normalization: counts

arguments:
  - name: --model
    type: file
    description: |
      An MLflow model URI for the UCE model. If it is a .zip or
      .tar.gz file it will be extracted to a temporary directory.
    required: true

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  - path: /src/utils/exit_codes.py
  - path: requirements.txt

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: docker
        add: https://astral.sh/uv/0.7.19/install.sh /uv-installer.sh
        run: sh /uv-installer.sh && rm /uv-installer.sh
        env: PATH="/root/.local/bin/:$PATH"
      - type: docker
        run: uv venv --python 3.11 /opt/venv
      - type: docker
        env:
          - VIRTUAL_ENV=/opt/venv
          - PATH="/opt/venv/bin:$PATH"
        add: requirements.txt /requirements.txt
        run: uv pip install -r /requirements.txt
      - type: docker
        run: uv pip install mlflow==3.1.0
      - type: docker
        run: uv pip install git+https://github.com/openproblems-bio/core#subdirectory=packages/python/openproblems

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu, gpu]
