__merge__: ../../api/base_method.yaml

name: uce_mlflow
label: UCE (MLflow model)
summary: UCE offers a unified biological latent space that can represent any cell
description: |
  Universal Cell Embedding (UCE) is a single-cell foundation model that offers a
  unified biological latent space that can represent any cell, regardless of
  tissue or species

  Here, we use a version packaged as an MLflow model.
references:
  doi:
    - 10.1101/2023.11.28.568918
links:
  documentation: https://github.com/snap-stanford/UCE/blob/main/README.md
  repository: https://github.com/snap-stanford/UCE

info:
  method_types: [embedding]
  preferred_normalization: counts

arguments:
  - name: --model
    type: file
    description: |
      An MLflow model URI for the UCE model. If it is a .zip or
      .tar.gz file it will be extracted to a temporary directory.
    required: true

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  - path: /src/utils/exit_codes.py
  - path: /src/utils/unpack.py
  - path: /src/utils/mlflow.py
  - path: requirements.txt

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    __merge__: /src/utils/mlflow_docker_setup.yaml

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu, gpu]
