__merge__: /src/api/comp_metric.yaml
name: asw_batch
info:
  metric_type: embedding
  metrics:
    - name: asw_batch
      label: ASW batch
      summary: Modified average silhouette width (ASW) of batch
      # TODO: transform into more readable markdown with proper formulae formatting
      description: |
          We consider the absolute silhouette width, s(i), on
          batch labels per cell i. Here, 0 indicates that batches are well mixed, and any
          deviation from 0 indicates a batch effect:
          𝑠batch(𝑖)=|𝑠(𝑖)|.

          To ensure higher scores indicate better batch mixing, these scores are scaled by
          subtracting them from 1. As we expect batches to integrate within cell identity
          clusters, we compute the batchASWj score for each cell label j separately,
          using the equation:
          batchASW𝑗=1|𝐶𝑗|∑𝑖∈𝐶𝑗1−𝑠batch(𝑖),

          where Cj is the set of cells with the cell label j and |Cj| denotes the number of cells
          in that set.

          To obtain the final batchASW score, the label-specific batchASWj scores are averaged:
          batchASW=1|𝑀|∑𝑗∈𝑀batchASW𝑗.

          Here, M is the set of unique cell labels.
      references:
        doi: 10.1038/s41592-021-01336-8
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - scib==1.1.7
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, lowcpu]
