__merge__: /src/api/comp_method.yaml
name: fastmnn
label: fastMnn
summary: A simpler version of the original mnnCorrect algorithm.
description: |
  The fastMNN() approach is much simpler than the original mnnCorrect() algorithm, and proceeds in several steps.

  1. Perform a multi-sample PCA on the (cosine-)normalized expression values to reduce dimensionality.
  2. Identify MNN pairs in the low-dimensional space between a reference batch and a target batch.
  3. Remove variation along the average batch vector in both reference and target batches.
  4. Correct the cells in the target batch towards the reference, using locally weighted correction vectors.
  5. Merge the corrected target batch with the reference, and repeat with the next target batch.
references:
  doi: 10.1038/nbt.4091
links:
  repository: https://code.bioconductor.org/browse/batchelor/
  documentation: https://bioconductor.org/packages/batchelor/
info:
  method_types: [feature, embedding]
  preferred_normalization: log_cp10k
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc: batchelor
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, lowcpu, highmem]
