name: run_benchmark
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input_dataset"
        __merge__: /src/api/file_dataset.yaml
        type: file
        direction: input
        required: true
      - name: "--input_solution"
        __merge__: /src/api/file_solution.yaml
        type: file
        direction: input
        required: true
  - name: Outputs
    arguments:
      - name: "--output_scores"
        type: file
        required: true
        direction: output
        description: A yaml file containing the scores of each of the methods
        default: score_uns.yaml
      - name: "--output_method_configs"
        type: file
        required: true
        direction: output
        default: method_configs.yaml
      - name: "--output_metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
      - name: "--output_dataset_info"
        type: file
        required: true
        direction: output
        default: dataset_uns.yaml
      - name: "--output_task_info"
        type: file
        required: true
        direction: output
        default: task_info.yaml
  - name: Methods
    arguments:
      - name: "--method_ids"
        type: string
        multiple: true
        description: A list of method ids to run. If not specified, all methods will be run.

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /_viash.yaml

dependencies:
  - name: h5ad/extract_uns_metadata
    repository: core
  - name: control_methods/embed_cell_types
  - name: control_methods/embed_cell_types_jittered
  - name: control_methods/no_integration
  - name: control_methods/no_integration_batch
  - name: control_methods/shuffle_integration
  - name: control_methods/shuffle_integration_by_batch
  - name: control_methods/shuffle_integration_by_cell_type
  - name: methods/bbknn
  - name: methods/combat
  - name: methods/fastmnn
  - name: methods/liger
  - name: methods/mnn_correct
  - name: methods/mnnpy
  - name: methods/pyliger
  - name: methods/scalex
  - name: methods/scanorama
  - name: methods/scanvi
  - name: methods/scvi
  - name: metrics/asw_batch
  - name: metrics/asw_label
  - name: metrics/cell_cycle_conservation
  - name: metrics/clustering_overlap
  - name: metrics/graph_connectivity
  - name: metrics/hvg_overlap
  - name: metrics/isolated_label_asw
  - name: metrics/isolated_label_f1
  - name: metrics/kbet
  - name: metrics/lisi
  - name: metrics/pcr
  - name: data_processors/transform

runners:
  - type: nextflow
