name: "drvi"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    label: "Dataset"
    summary: "Unintegrated AnnData HDF5 file."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        obs:
        - type: "string"
          name: "cell_type"
          description: "Cell type information"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        - type: "string"
          name: "feature_id"
          description: "A database identifier for the feature, usually an ENSEMBL\
            \ ID."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        obsp:
        - type: "double"
          name: "knn_distances"
          description: "K nearest neighbors distance matrix."
          required: true
        - type: "double"
          name: "knn_connectivities"
          description: "K nearest neighbors connectivities matrix."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "object"
          name: "knn"
          description: "Supplementary K nearest neighbors data."
          required: true
    example:
    - "resources_test/task_batch_integration/cxg_immune_cell_atlas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Integration"
    summary: "An integrated AnnData dataset."
    description: "Must contain at least one of:\n\n  - Feature: the corrected_counts\
      \ layer\n  - Embedding: the X_emb obsm\n  - Graph: the connectivities and distances\
      \ obsp\n"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "double"
          name: "corrected_counts"
          description: "Feature output - corrected counts"
          required: false
        obsm:
        - type: "double"
          name: "X_emb"
          description: "Embedding output - 2D coordinate matrix"
          required: false
        obsp:
        - type: "double"
          name: "connectivities"
          description: "Graph output - neighbor connectivities matrix"
          required: false
        - type: "double"
          name: "distances"
          description: "Graph output - neighbor distances matrix"
          required: false
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "object"
          name: "neighbors"
          description: "Supplementary K nearest neighbors data."
          required: false
    example:
    - "resources_test/task_batch_integration/cxg_immune_cell_atlas/integrated.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_hvg"
    description: "Number of highly variable genes to use."
    info: null
    default:
    - 2000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_epochs"
    description: "Number of epochs"
    info: null
    default:
    - 100
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
- type: "file"
  path: "read_anndata_partial.py"
label: "DRVI"
summary: "DrVI is an unsupervised generative model capable of learning non-linear\
  \ interpretable disentangled latent representations from single-cell count data."
description: "Disentangled Representation Variational Inference (DRVI) is an unsupervised\
  \ deep generative model designed for integrating single-cell RNA sequencing (scRNA-seq)\
  \ data across different batches.\nIt extends the variational autoencoder (VAE) framework\
  \ by learning a latent representation that captures biological variation while disentangling\
  \ and correcting for batch effects.\nDRVI conditions both the encoder and decoder\
  \ on batch covariates, allowing it to explicitly model and mitigate batch-specific\
  \ variations during training.\nBy incorporating a KL-divergence regularization term,\
  \ it balances data reconstruction with latent space structure, resulting in a unified\
  \ embedding where similar cells cluster together regardless of batch.\n"
test_resources:
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "file"
  path: "resources_test/task_batch_integration/cxg_immune_cell_atlas"
  dest: "resources_test/task_batch_integration/cxg_immune_cell_atlas"
info:
  preferred_normalization: "counts"
  type: "method"
  type_info:
    label: "Method"
    summary: "A method for the batch integration task."
    description: "A batch integration method which integrates multiple datasets.\n"
status: "enabled"
scope:
  image: "public"
  target: "public"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
license: "MIT"
references:
  doi:
  - "10.1101/2024.11.06.622266"
links:
  repository: "https://github.com/theislab/DRVI?tab=readme-ov-file"
  docker_registry: "ghcr.io"
  documentation: "https://drvi.readthedocs.io/latest/index.html"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_pytorch_nvidia:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    pypi:
    - "drvi-py==0.1.7"
    - "torch==2.3.0"
    - "torchvision==0.18.0"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/drvi/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/methods/drvi"
  executable: "target/executable/methods/drvi/drvi"
  viash_version: "0.9.4"
  git_commit: "37df0e7dad0a31dbc45d9fbc6a49450bc4d05dfe"
  git_remote: "https://github.com/openproblems-bio/task_batch_integration"
package_config:
  name: "task_batch_integration"
  version: "build_main"
  label: "Batch Integration"
  summary: "Remove unwanted batch effects from scRNA-seq data while retaining biologically\
    \ meaningful variation."
  description: "As single-cell technologies advance, single-cell datasets are growing\
    \ both in size and complexity.\nEspecially in consortia such as the Human Cell\
    \ Atlas, individual studies combine data from multiple labs, each sequencing multiple\
    \ individuals possibly with different technologies.\nThis gives rise to complex\
    \ batch effects in the data that must be computationally removed to perform a\
    \ joint analysis.\nThese batch integration methods must remove the batch effect\
    \ while not removing relevant biological information.\nCurrently, over 200 tools\
    \ exist that aim to remove batch effects scRNA-seq datasets [@zappia2018exploring].\n\
    These methods balance the removal of batch effects with the conservation of nuanced\
    \ biological information in different ways.\nThis abundance of tools has complicated\
    \ batch integration method choice, leading to several benchmarks on this topic\
    \ [@luecken2022benchmarking; @tran2020benchmark; @chazarragil2021flexible; @mereu2020benchmarking].\n\
    Yet, benchmarks use different metrics, method implementations and datasets. Here\
    \ we build a living benchmarking task for batch integration methods with the vision\
    \ of improving the consistency of method evaluation.\n\nIn this task we evaluate\
    \ batch integration methods on their ability to remove batch effects in the data\
    \ while conserving variation attributed to biological effects.\nAs input, methods\
    \ require either normalised or unnormalised data with multiple batches and consistent\
    \ cell type labels.\nThe batch integrated output can be a feature matrix, a low\
    \ dimensional embedding and/or a neighbourhood graph.\nThe respective batch-integrated\
    \ representation is then evaluated using sets of metrics that capture how well\
    \ batch effects are removed and whether biological variance is conserved.\nWe\
    \ have based this particular task on the latest, and most extensive benchmark\
    \ of single-cell data integration methods.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/cxg_immune_cell_atlas/"
      dest: "resources_test/common/cxg_immune_cell_atlas"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_batch_integration/"
      dest: "resources_test/task_batch_integration"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Michaela Mueller"
    roles:
    - "maintainer"
    - "author"
    info:
      github: "mumichae"
      orcid: "0000-0002-1401-1785"
  - name: "Malte Luecken"
    roles:
    - "author"
    info:
      github: "LuckyMD"
      orcid: "0000-0001-7464-7921"
  - name: "Daniel Strobl"
    roles:
    - "author"
    info:
      github: "danielStrobl"
      orcid: "0000-0002-5516-7057"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Luke Zappia"
    roles:
    - "author"
    info:
      github: "lazappi"
      orcid: "0000-0001-7744-8565"
  - name: "Scott Gigante"
    roles:
    - "contributor"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Kai Waldrant"
    roles:
    - "contributor"
    info:
      github: "KaiWaldrant"
      orcid: "0009-0003-8555-1361"
  - name: "Martin Kim"
    roles:
    - "contributor"
    info:
      github: "martinkim0"
      orcid: "0009-0003-8555-1361"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  - name: "Jeremie Kalfon"
    roles:
    - "contributor"
    info:
      github: "jkobject"
      orcid: "0000-0002-2818-9728"
  keywords:
  - "batch integration"
  - "scRNA-seq"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.1038/s41592-021-01336-8"
  links:
    repository: "https://github.com/openproblems-bio/task_batch_integration"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_batch_integration/issues"
