__merge__: /src/api/comp_method.yaml
name: harmonypy
label: Harmonypy
summary: harmonypy is a port of the harmony R package by Ilya Korsunsky.
description: |
  Harmony is a general-purpose R package with an efficient algorithm for integrating multiple data sets.
  It is especially useful for large single-cell datasets such as single-cell RNA-seq.
references:
  # Korsunsky, I., Millard, N., Fan, J. et al.
  # Fast, sensitive and accurate integration of single-cell data with Harmony.
  # Nat Methods 16, 1289–1296 (2019). https://doi.org/10.1038/s41592-019-0619-0
  doi: 10.1038/s41592-019-0619-0
links:
  repository: https://github.com/slowkow/harmonypy
  documentation: https://portals.broadinstitute.org/harmony
info:
  method_types: [embedding]
  preferred_normalization: log_cp10k
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - harmonypy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowcpu, highmem, hightime]
