__merge__: /src/api/comp_metric.yaml
name: clustering_overlap
info:
  metric_type: graph
  metrics:
    - name: ari
      label: ARI
      summary: Adjusted Rand Index compares clustering overlap, correcting for random
        labels and considering correct overlaps and disagreements.
      description: |
        The Adjusted Rand Index (ARI) compares the overlap of two clusterings;
        it considers both correct clustering overlaps while also counting correct
        disagreements between two clusterings.
        We compared the cell-type labels with the NMI-optimized
        Louvain clustering computed on the integrated dataset.
        The adjustment of the Rand index corrects for randomly correct labels.
        An ARI of 0 or 1 corresponds to random labeling or a perfect match,
        respectively.
      references:
        doi:
          - 10.1038/s41592-021-01336-8
          - 10.1007/bf01908075
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
    - name: nmi
      label: NMI
      summary: NMI compares overlap by scaling using mean entropy terms and optimizing
        Louvain clustering to obtain the best match between clusters and labels.
      description: |
        Normalized Mutual Information (NMI) compares the overlap of two clusterings.
        We used NMI to compare the cell-type labels with Louvain clusters computed on
        the integrated dataset. The overlap was scaled using the mean of the entropy terms
        for cell-type and cluster labels. Thus, NMI scores of 0 or 1 correspond to uncorrelated
        clustering or a perfect match, respectively. We performed optimized Louvain clustering
        for this metric to obtain the best match between clusters and labels.
      references:
        doi:
          - 10.1145/2808797.2809344
          - 10.1038/s41592-021-01336-8
      links:
        homepage: https://scib.readthedocs.io/en/latest/
        documentation: https://scib.readthedocs.io/en/latest/api/scib.metrics.silhouette_batch.html
        repository: https://github.com/theislab/scib
      min: 0
      max: 1
      maximize: true
arguments:
  - name: --resolutions
    type: double
    multiple: true
    default: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
    description: Resolution parameter for clustering, looking for precomputed clusters of that resolution
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - scib==1.1.7
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, lowcpu]
