__merge__: /src/api/comp_method.yaml
name: liger
label: LIGER
summary: Linked Inference of Genomic Experimental Relationships
description: |
  LIGER or linked inference of genomic experimental relationships uses iNMF
  deriving and implementing a novel coordinate descent algorithm to efficiently
  do the factorization. Joint clustering is performed and factor loadings are
  normalised.
references:
  doi: 10.1016/j.cell.2019.05.006
links:
  repository: https://github.com/welch-lab/liger
  documentation: https://github.com/welch-lab/liger
info:
  method_types: [embedding]
  preferred_normalization: log_cp10k
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: apt
        packages: cmake
      - type: r
        cran: rliger
        github: welch-lab/RcppPlanc
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowcpu, highmem, hightime]
